name: kb_checker
description: A keyboard tester.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  adaptive_theme: any
  bitsdojo_window: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # fluentui_system_icons: any
  intl: any
  package_info_plus: any
  url_launcher: any
  window_manager: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/