name: Build desktop app

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Set up Flutter actions
      uses: subosito/flutter-action@v2.12.0
      with:
        flutter-version: '3.10.2'

    - name: Enable Windows support
      run: flutter config --enable-windows-desktop

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter for Windows
      run: flutter build windows --release

    - name: Get version from pubspec.yaml
      id: version
      run: |
        echo "::set-output name=version::$(grep 'version:' ./pubspec.yaml | cut -d ' ' -f 2)"

    - name: Compress artifacts
      run: |
        Compress-Archive -Path build/windows/runner/Release/* -DestinationPath ${{ steps.version.outputs.version }}.zip
        
    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "${{ steps.version.outputs.version }}.zip"
        name: Release ${{ steps.version.outputs.version }}
        tag: "v.${{ steps.version.outputs.version }}"
        token: ${{ secrets.KB_CHECKER_TOKEN }}
            